// Combined Claude Pro + ChatGPT Plus widget for Scriptable.
// Copy this file into Scriptable, then replace both CONFIG values locally.
const CONFIG = { baseUrl: "https://YOUR-PRIVATE-HOST", apiKey: "PASTE-YOUR-API-KEY", refreshMinutes: 30 };
const COLORS = { bg: new Color("#1a1a1a"), muted: new Color("#999999"), claude: new Color("#DA7756"), chatgpt: new Color("#10A37F") };

function color(pct) { return new Color(pct < 50 ? "#34c759" : pct < 75 ? "#ffcc00" : pct < 90 ? "#ff9500" : "#ff3b30"); }
function circle(c) { const d = new DrawContext(); d.size = new Size(10, 10); d.opaque = false; d.setFillColor(c); const p=new Path(); p.addEllipse(new Rect(0,0,10,10)); d.addPath(p); d.fillPath(); return d.getImage(); }
function header(parent, name, brand) { const s = parent.addStack(); s.layoutHorizontally(); s.centerAlignContent(); const i=s.addImage(circle(brand)); i.imageSize=new Size(10,10); s.addSpacer(6); const t=s.addText(name); t.font=Font.boldSystemFont(14); t.textColor=Color.white(); }
function bar(pct, width) { const d=new DrawContext(); d.size=new Size(width,8); d.opaque=false; d.setFillColor(new Color("#353535")); d.fillRoundedRect(new Rect(0,0,width,8),4,4); d.setFillColor(color(pct)); d.fillRoundedRect(new Rect(0,0,Math.max(8,Math.min(width,width*pct/100)),8),4,4); return d.getImage(); }
function row(parent,label,pct,width) { const s=parent.addStack(); s.layoutHorizontally(); s.centerAlignContent(); const l=s.addText(label); l.font=Font.systemFont(12); l.textColor=COLORS.muted; s.addSpacer(); if (typeof pct!=="number") { const x=s.addText("—"); x.textColor=COLORS.muted; return; } const i=s.addImage(bar(pct,width)); i.imageSize=new Size(width,8); s.addSpacer(6); const v=s.addText(`${Math.round(pct)}%`); v.font=Font.boldSystemFont(12); v.textColor=color(pct); }
function date(v) { if (!v) return "—"; const d=new Date(v); return isNaN(d) ? "—" : `${d.getDate()}/${d.getMonth()+1}`; }
function projection(parent,p) { if (!p || p.status !== "ok") return; parent.addSpacer(3); const pace=parent.addText(`Pace +${p.pct_per_hour}%/jam`); pace.font=Font.systemFont(10); pace.textColor=COLORS.muted; const safe=p.safe_until_reset; const t=parent.addText(safe ? `✅ Aman (~${p.projected_pct_at_reset}% saat reset)` : `⚠️ Habis ~${date(p.limit_reached_at)} (${p.projected_pct_at_reset}%)`); t.font=Font.boldSystemFont(10); t.textColor=safe ? new Color("#34c759") : new Color("#ff9500"); t.lineLimit=1; }
async function get(path) { const r=new Request(CONFIG.baseUrl+path); r.headers={"X-API-Key":CONFIG.apiKey}; r.timeoutInterval=15; return r.loadJSON(); }
const fm=FileManager.local(), cache=fm.joinPath(fm.documentsDirectory(),"ai_usage_widget_cache.json");
async function load() { const cached=fm.fileExists(cache) ? JSON.parse(fm.readString(cache)) : {}; const [claude,chatgpt]=await Promise.all([get("/api/claude-usage").catch(()=>cached.claude),get("/api/chatgpt-usage").catch(()=>cached.chatgpt)]); if (!claude && !chatgpt) throw new Error("offline"); const d={claude,chatgpt}; fm.writeString(cache,JSON.stringify(d)); return d; }
function section(parent, label, brand, rows, proj, width) { header(parent,label,brand); parent.addSpacer(5); rows.forEach(([n,p])=>{row(parent,n,p,width);parent.addSpacer(3);}); projection(parent,proj); }
const w=new ListWidget(); w.backgroundColor=COLORS.bg; w.setPadding(12,14,12,14); let d;
try { d=await load(); const c=d.claude||{}, g=d.chatgpt||{}; if (config.widgetFamily==="small") { section(w,"Claude Pro",COLORS.claude,[["Weekly",c.weekly?.pct_actual]],null,80); w.addSpacer(8); section(w,"ChatGPT Plus",COLORS.chatgpt,[[g.windows?.[0]?.label||"Usage",g.windows?.[0]?.used_percent]],null,80); } else if (config.widgetFamily==="medium") { const r=w.addStack(); r.layoutHorizontally(); const a=r.addStack();a.layoutVertically();section(a,"Claude Pro",COLORS.claude,[["Weekly",c.weekly?.pct_actual],["Session",c.session?.pct_actual]],null,65);r.addSpacer(16);const b=r.addStack();b.layoutVertically();section(b,"ChatGPT Plus",COLORS.chatgpt,(g.windows||[]).slice(0,2).map(x=>[x.label,x.used_percent]),null,65); } else { section(w,"Claude Pro",COLORS.claude,[["Weekly",c.weekly?.pct_actual],["Session",c.session?.pct_actual]],c.projection,155);w.addSpacer(12);const p=(g.projections||[])[0];section(w,"ChatGPT Plus",COLORS.chatgpt,(g.windows||[]).slice(0,2).map(x=>[x.label,x.used_percent]),p,155); } } catch (e) { const t=w.addText("AI Usage unavailable");t.font=Font.boldSystemFont(14);t.textColor=Color.white(); const x=w.addText(String(e).includes("401")?"Check API key":"Check server connection");x.textColor=COLORS.muted; }
w.refreshAfterDate=new Date(Date.now()+CONFIG.refreshMinutes*60*1000); Script.setWidget(w); Script.complete();
