// Claude Pro-only Scriptable widget. Set these two values locally; do not commit them.
const CONFIG = { baseUrl: "https://YOUR-PRIVATE-HOST", apiKey: "PASTE-YOUR-API-KEY", refreshMinutes: 30 };
const fm=FileManager.local(), cache=fm.joinPath(fm.documentsDirectory(),"claude_usage_widget_cache.json");
const brand=new Color("#DA7756"), muted=new Color("#999999");
function color(p){return new Color(p<50?"#34c759":p<75?"#ffcc00":p<90?"#ff9500":"#ff3b30");}
function dot(){const c=new DrawContext();c.size=new Size(10,10);c.opaque=false;c.setFillColor(brand);const p=new Path();p.addEllipse(new Rect(0,0,10,10));c.addPath(p);c.fillPath();return c.getImage();}
function bar(p,w){const c=new DrawContext();c.size=new Size(w,8);c.opaque=false;c.setFillColor(new Color("#353535"));c.fillRoundedRect(new Rect(0,0,w,8),4,4);c.setFillColor(color(p));c.fillRoundedRect(new Rect(0,0,Math.max(8,Math.min(w,w*p/100)),8),4,4);return c.getImage();}
function row(w,label,pct,width){const s=w.addStack();s.layoutHorizontally();s.centerAlignContent();const l=s.addText(label);l.font=Font.systemFont(12);l.textColor=muted;s.addSpacer();if(typeof pct!=="number"){const n=s.addText("—");n.textColor=muted;return;}const i=s.addImage(bar(pct,width));i.imageSize=new Size(width,8);s.addSpacer(6);const t=s.addText(`${Math.round(pct)}%`);t.font=Font.boldSystemFont(12);t.textColor=color(pct);}
async function load(){try{const r=new Request(CONFIG.baseUrl+"/api/claude-usage");r.headers={"X-API-Key":CONFIG.apiKey};r.timeoutInterval=15;const d=await r.loadJSON();fm.writeString(cache,JSON.stringify(d));return d;}catch(e){if(fm.fileExists(cache))return JSON.parse(fm.readString(cache));throw e;}}
const w=new ListWidget();w.backgroundColor=new Color("#1a1a1a");w.setPadding(12,14,12,14);try{const d=await load(),h=w.addStack();h.layoutHorizontally();const i=h.addImage(dot());i.imageSize=new Size(10,10);h.addSpacer(6);const t=h.addText("Claude Pro");t.font=Font.boldSystemFont(15);t.textColor=Color.white();w.addSpacer(8);row(w,"Weekly",d.weekly?.pct_actual,160);w.addSpacer(5);row(w,"Session",d.session?.pct_actual,160);const p=d.projection;if(p?.status==="ok"){w.addSpacer(7);const pace=w.addText(`Pace +${p.pct_per_hour}%/jam`);pace.font=Font.systemFont(11);pace.textColor=muted;const status=w.addText(p.safe_until_reset?`✅ Aman (~${p.projected_pct_at_reset}% saat reset)`:`⚠️ Proyeksi ${p.projected_pct_at_reset}% saat reset`);status.font=Font.boldSystemFont(11);status.textColor=p.safe_until_reset?new Color("#34c759"):new Color("#ff9500");}}catch(e){const t=w.addText("Claude Usage unavailable");t.textColor=Color.white();}w.refreshAfterDate=new Date(Date.now()+CONFIG.refreshMinutes*60000);Script.setWidget(w);Script.complete();
